### ISSUE TITLE
FATAL:  error opening file "/sys/fs/cgroup/memory/postgres/107533/memory.memsw.limit_in_bytes"

### ISSUE THREAD

**Issue by jwpit** [cybertec-postgresql/pg_cgroups#1]
Hi Laurenz,

loading pg_cgroups fails, if memory.memsw.limit_in_bytes is not available on the system:
`ls: cannot access '/sys/fs/cgroup/memory/init.scope/memory.memsw.limit_in_bytes': No such file or directory`
Shouldn't this be made optional?

Jens

**Comment by laurenz** [comment]
I am surprised that there is no such file.

Can you tell me more about your system? What version of what Linux distribution is that?

Could it be that you are using cgroups v2? pg_cgroups currently supports only v1.
What do you get for

    mount | grep cgroup

**Comment by jwpit** [comment]
Hi Laurenz,

it's Debian Buster
```
$ uname -a
Linux sql21 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

$ dpkg -l|grep cgroup
ii  cgroup-tools                         0.41-8.1                    amd64        control and monitor control groups (tools)
ii  libcgroup1:amd64                     0.41-8.1                    amd64        control and monitor control groups (library)

$ mount | grep cgroup
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
```

**Comment by laurenz** [comment]
I checked, and it seems like the file is only present if the kernel was configured with `CONFIG_MEMCG_SWAP_ENABLED=y`.

Could you verify that that is not the case on your system?

The config might be in several places:
- `/proc/config.gz`
- `/lib/modules/$(uname -r)/config`
- `/boot/config`
- `/boot/config-$(uname -r)`

**Comment by jwpit** [comment]
```
$ grep CONFIG_MEMCG_SWAP_ENABLED /boot/config-$(uname -r)
# CONFIG_MEMCG_SWAP_ENABLED is not set
```

**Comment by laurenz** [comment]
Ok, I'll have to fix the software so that it survives on system that lack the parameter.

**Comment by laurenz** [comment]
Can you try [the fixed version](https://github.com/cybertec-postgresql/pg_cgroups/archive/handle_missing_swap_parameters.zip) and tell me if that fixes the problem for you?

**Comment by laurenz** [comment]
Could you give me some feedback on his one?

I'd like a confirmation that this fixes the problem.
I have no test system with a strange configuration as that.

**Comment by jwpit** [comment]
It's just the plain Debian default.
origin/handle_missing_swap_parameters fails:
2019-12-10 10:00:35.458 CET [141124] 0, FATAL:  error opening file "/sys/fs/cgroup/memory/postgres/memory.memsw.limit_in_bytes" for reading: No such file or directory

**Comment by laurenz** [comment]
Thanks a lot for checking!

I made a stupid error, fixed.
Could you give [it](https://github.com/cybertec-postgresql/pg_cgroups/archive/handle_missing_swap_parameters.zip) another test?

**Comment by laurenz** [comment]
Thanks again for the report and the confirmation that the fix works!
